services:
                              ## PostgreSQL Services
  
  # PostgreSQL for User Service
  postgres_user_db_service:
    image: postgres:16
    container_name: postgres_user_db_service
    env_file:
      - ./user_service/.env
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
      - ./init_db/user_db.sql:/docker-entrypoint-initdb.d/user_db.sql
    networks:
      - backend

  # PostgreSQL for Chat Service
  postgres_chat_db_service:
    image: postgres:16
    container_name: postgres_chat_db_service
    env_file:
      - ./chat_service/.env
    volumes:
      - postgres_chat_data:/var/lib/postgresql/data
      - ./init_db/chat_db.sql:/docker-entrypoint-initdb.d/chat_db.sql
    networks:
      - backend

  # PostgreSQL for Custom GPT Service
  postgres_gpt_db_service:
    image: postgres:16
    container_name: postgres_gpt_db_service
    env_file:
      - ./custom_gpt_service/.env
    volumes:
      - postgres_gpt_data:/var/lib/postgresql/data
      - ./init_db/gpt_db.sql:/docker-entrypoint-initdb.d/gpt_db.sql
    networks:
      - backend

  # PostgreSQL for Chat Memory Service
  postgres_chat_memory_service:
    image: postgres:16
    container_name: postgres_chat_memory_service
    environment:
      POSTGRES_DB: chat_memory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sunil
    volumes:
      - postgres_memory_data:/var/lib/postgresql/data
    networks:
      - backend

                              ## Main Services

  # User Service
  user_service:
    build:
      context: ./user_service
    container_name: user_service
    depends_on:
      - postgres_user_db_service
    ports:
      - "8000:8000"
    volumes:
      - ./user_service:/app
    networks:
      - backend
    env_file:
      - ./user_service/.env

  # Chat Service
  chat_service:
    build:
      context: ./chat_service
    container_name: chat_service
    depends_on:
      - postgres_chat_db_service
      - postgres_chat_memory_service
    ports:
      - "8001:8000"
    volumes:
      - ./chat_service:/app
    networks:
      - backend
    env_file:
      - ./chat_service/.env

  # Custom GPT Service
  custom_gpt_service:
    build:
      context: ./custom_gpt_service
    container_name: custom_gpt_service
    depends_on:
      - postgres_gpt_db_service
      - postgres_chat_memory_service
    ports:
      - "8002:8000"
    volumes:
      - ./custom_gpt_service:/app
    networks:
      - backend
    env_file:
      - ./custom_gpt_service/.env

  api_gateway:
    build:
      context: ./gateway
    container_name: api_gateway
    ports:
      - "8003:8000"
    networks:
      - frontend

volumes:
  postgres_user_data:
  postgres_chat_data:
  postgres_gpt_data:
  postgres_memory_data:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
